---
title: "CLIL Data Science Reflections"
author: "Your name"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_download: true
---

<details>

<summary>Click for Details</summary> Every week, after you finish working through the content, I want to hear about what you learned and what questions you still have. To facilitate this, and to encourage engagement with the course content, you'll need to take brief notes and upload them to the **ouR Reflections** on Moodle ***by noon*** of the day of the next class.

You should answer these two-three questions each time:

-   1a. What was the most interesting thing you learned about data?

-   1b. What was the most interesting thing you learned about R?

-   2\. What was the least clear thing from the class this week? What are you still wondering about?

This document will end up being a record of your learning through this course. Quite quickly, you will be able to add code chunks to your reflections and show some simple analysis or visualisations too.

(To add chunks of code either type **ctrl** + **alt** + **i** on Windows, or **⌘** + **⌥** + **i** on macOS, or use the "Insert Chunk" menu.)

These notes will be worth 20% of your final grade using a check system:

-   ✔+: (*1.5 points (150%)*) Response shows phenomenal thought and engagement with the course content. I will not assign these often.
-   ✔: (*1 point (100%)*) Response is thoughtful, well-written, and shows engagement with the course content. This is the expected level of performance.
-   ✔−: (*).5 points (50%)*) Response is hastily composed, too short, and/or only barely engages with the course content. This grade signals that you need to improve next time. I will hopefully not assign these often.

There will also be up to 3 bonus points for completing all the reflections over the semester.

Notice that is essentially a pass/fail or completion-based system. I'm not grading your writing ability, I'm not counting the exact number of words you're writing, I'm just looking for thoughtful engagement, that's all.

</details>

### Week 1

1a There are many forms of data!

1b R code uses dollar signs, but it's free?!

2 I'm still not sure about saving files.

### Week 2

### Week 3

### Week 4

### Week 5

### Week 6

### Week 7

### Week 8

### Week 9

### Week 10

### Week 11

### Week 12

### Week 13

### Week 14
